# site settings
title: Hyperparam Blog
description: Insights on browser-based AI data visualization and exploration. See how better data builds smarter, more reliable models.
url: "https://hyparam.github.io/blog"
twitter_username: hyperparamapp
github_username: hyparam

# Social media and SEO
author:
  name: Hyperparam Team
  twitter: hyperparamapp
twitter:
  username: hyperparamapp
  card: summary_large_image
social:
  name: Hyperparam
  links:
    - https://twitter.com/hyperparamapp
    - https://github.com/hyparam
logo: /assets/favicon.svg

# Build settings
permalink: pretty
theme: minima
