# site settings
title: Hyperparam Blog
description: Notes on working with LLM datasets in the browser.
url: "https://blog.hyperparam.app"
twitter_username: hyperparamapp
github_username: hyparam
linkedin_username: hyperparam

# Social media and SEO
twitter:
  username: hyperparamapp
  card: summary_large_image
social:
  name: Hyperparam
  links:
    - https://twitter.com/hyperparamapp
    - https://github.com/hyparam
    - https://www.linkedin.com/company/hyperparam/
logo: /assets/favicon.svg

# Build settings
permalink: /:title/
theme: minima
